### ISSUE TITLE
Failure to Build

### ISSUE THREAD

**Issue by Mercury39** [iraizo/breathless-fork#5]
The project failed to build due to issues listed below.

After following instructions from the Wiki the project failed to build.

issues in **esp.cpp**:
![image](https://user-images.githubusercontent.com/48383417/54071754-54c99b80-42c5-11e9-9892-c463c691b5a0.png)

![image](https://user-images.githubusercontent.com/48383417/54071816-24363180-42c6-11e9-9a45-3ad078c04800.png)

Issues in **hooks.cpp**:
![image](https://user-images.githubusercontent.com/48383417/54071764-85113a00-42c5-11e9-8671-81414e8f5155.png)

Issue in **IClientEntityList.h**:
![image](https://user-images.githubusercontent.com/48383417/54071774-a96d1680-42c5-11e9-9fa2-7ae652f5e73a.png)

Issue in **menu.cpp**:
![image](https://user-images.githubusercontent.com/48383417/54071807-0ec10780-42c6-11e9-938c-51818be83934.png)

Many Issues in **resolver.cpp**
![image](https://user-images.githubusercontent.com/48383417/54071849-8000ba80-42c6-11e9-95cf-b8f1aa266ea6.png)

![image](https://user-images.githubusercontent.com/48383417/54071854-927af400-42c6-11e9-8b7d-264ce0d58d03.png) **Same issue in line 429**

I am running macOS High Sierra version 10.13.6

**Comment by iraizo** [comment]
Fixed
