### ISSUE TITLE
CS:GO Crashes after Injecting the hack

### ISSUE THREAD

**Issue by tpincapps** [iraizo/breathless-fork#6]
**Describe the bug**
So the bug now is that it properly injects, yes, but when you go into a match, csgo crashes, as the offsets changes

**Additional context**
Any idea on how to update the offsets? thx

**Comment by yeet4206** [comment]
how do u even inject

**Comment by tpincapps** [comment]
I use lib2proc: https://www.unknowncheats.me/forum/pc-software/214802-lib2proc-definitive-os-macos-injector.html
for injecting the hack, osxinj doesn't work for me so yeah
